<a href="https://colab.research.google.com/github/sai-madhu-0409/BLANK/blob/main/Day1Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Converting a List to Array

In [2]:
lst=[1,2,3,4]
print(type(lst))
arr=np.array(lst)
print(type(arr))
print(arr)
arr=np.array(lst,ndmin=2)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]
<class 'numpy.ndarray'>


# 2. Arrange function

In [3]:
arr=np.arange(1,11,2)
arr


array([1, 3, 5, 7, 9])

In [ ]:
print(*arr)

1 3 5 7 9


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Total: ",arr.size)
print('rows: ',np.size(arr,0))
print('Cols: ',np.size(arr,1))

Total:  9
rows:  3
Cols:  3


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print((np.size(arr,0),np.size(arr,1)))
print(arr.shape)

(3, 3)
(3, 3)


In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([5.1,6.1,7.3,8.4])
print(arr1.dtype)
print(arr2.dtype)

int64
float64


In [ ]:
arr=np.zeros(shape=(3,5),dtype=int)
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
arr=np.ones(shape=(3,5),dtype=int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
np.eye(4,dtype=int)


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
np.empty(shape=(5,5))

array([[3.86593746e-315, 0.00000000e+000, 5.32004354e-317,
        5.32004354e-317, 6.51916316e-310],
       [6.51916329e-310, 6.51916316e-310, 6.51916329e-310,
        6.51916329e-310, 6.51916316e-310],
       [5.32006725e-317, 6.51916248e-310, 6.51916329e-310,
        5.32203561e-317, 6.51916329e-310],
       [6.51916329e-310, 5.32004354e-317, 6.51916316e-310,
        6.51916329e-310, 6.51916316e-310],
       [6.51916329e-310, 6.51916329e-310, 6.51916316e-310,
        5.32006725e-317, 6.51916248e-310]])